In [163]:
# from sklearn import svm,metrics
# from sklearn.neighbors import KNeighborsClassifier # 분류
# from sklearn.neighbors import KNeighborsRegressor  # 회귀-예측
from sklearn.linear_model import LinearRegression  # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [164]:
import pandas as pd
df = pd.read_csv('https://bit.ly/fish_csv')
df.head(3)

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Species   159 non-null    object 
 1   Weight    159 non-null    float64
 2   Length    159 non-null    float64
 3   Diagonal  159 non-null    float64
 4   Height    159 non-null    float64
 5   Width     159 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.6+ KB


In [166]:
df.describe()

Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [167]:
# 1. 데이터 전처리 -data,target 분리

fish_target = df['Species'].to_numpy()
fish_input = df.iloc[:,1:].to_numpy()

# train,test세트 분리
train_input,test_input,train_target,test_target = train_test_split(
    fish_input,fish_target, random_state=42
)

# 표준화 작업
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)




In [168]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_scaled,train_target)

LogisticRegression()

In [169]:
# 3. 데이터 예측
predict=lr.predict(test_scaled[:5])
print(predict)

# 기울기,y절편의 값을 적용시켜서 z점수 출력
# softmax함수를 적용해서 가장 높은 확률을 채택해서 결정함..


['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']


In [170]:
# 4. 데이터 정답률 - train,test
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.8067226890756303
0.85


### 결과값 도출 형태

In [171]:
proba = lr.predict_proba(train_scaled[:5])
np.round(proba,decimals=3)

array([[0.954, 0.01 , 0.012, 0.002, 0.004, 0.   , 0.017],
       [0.002, 0.   , 0.044, 0.941, 0.008, 0.   , 0.004],
       [0.   , 0.046, 0.105, 0.001, 0.061, 0.786, 0.001],
       [0.004, 0.029, 0.671, 0.013, 0.258, 0.012, 0.014],
       [0.074, 0.384, 0.209, 0.01 , 0.287, 0.016, 0.021]])

In [172]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision,decimals=2))

[[-2.35  0.75  2.54 -1.67  1.87  0.35 -1.49]
 [-4.17  1.38  2.1  -1.99  1.73  3.85 -2.9 ]
 [-1.45 -1.48  1.73  2.67  1.46 -1.83 -1.09]
 [ 0.02  0.26  2.18 -0.52  1.46 -3.   -0.39]
 [-2.22 -0.27  2.84 -0.4   1.84 -0.74 -1.06]]


In [173]:

from scipy.special import softmax

proba = softmax(decision,axis = 1)
print(np.round(proba,decimals=3))

[[0.004 0.091 0.545 0.008 0.28  0.061 0.01 ]
 [0.    0.061 0.127 0.002 0.087 0.722 0.001]
 [0.009 0.009 0.223 0.569 0.17  0.006 0.013]
 [0.061 0.077 0.527 0.036 0.257 0.003 0.04 ]
 [0.004 0.03  0.664 0.026 0.245 0.018 0.013]]


#### C=30, max_iter=1000 횟수를 늘려 정답률을 높이는 방법이다


In [174]:
# 2. 데이터 실습시키기
from sklearn.linear_model import LogisticRegression

# max_iter : 반복횟수=100 기본설정
# C규제 : 올라가면 규제가 약해짐, 낮아지면 규제가 강해짐, 선형회귀 규제 = alpha값으로 지정
lr = LogisticRegression(C=30, max_iter=1000)
lr.fit(train_scaled,train_target)

LogisticRegression(C=30, max_iter=1000)

In [175]:
print(lr.score(train_scaled,train_target))
print(lr.score(test_scaled,test_target))

0.9663865546218487
0.925


In [176]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [177]:
proba = lr.predict_proba(test_scaled[:5])
print( np.round(proba,decimals=3))

[[0.    0.009 0.882 0.    0.103 0.004 0.002]
 [0.    0.001 0.032 0.    0.005 0.962 0.   ]
 [0.    0.    0.024 0.927 0.008 0.041 0.   ]
 [0.007 0.032 0.256 0.005 0.617 0.    0.084]
 [0.    0.    0.927 0.002 0.068 0.002 0.001]]


In [178]:
from scipy.special import softmax

proba = softmax(decision,axis = 1)
print(np.round(proba,decimals=3))



[[0.004 0.091 0.545 0.008 0.28  0.061 0.01 ]
 [0.    0.061 0.127 0.002 0.087 0.722 0.001]
 [0.009 0.009 0.223 0.569 0.17  0.006 0.013]
 [0.061 0.077 0.527 0.036 0.257 0.003 0.04 ]
 [0.004 0.03  0.664 0.026 0.245 0.018 0.013]]
