In [7]:
from sklearn.linear_model import LinearRegression  # 선형회귀
from sklearn.preprocessing import PolynomialFeatures # 다항특성을 만들어주는 라이브러리
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import matplotlib
from tensorflow import keras
matplotlib.rcParams['axes.unicode_minus'] = False  # 마이너스 표시 해결
# 한글설정
matplotlib.rcParams['font.family'] = 'Malgun Gothic' # windows 사용자
# matplotlib.rcParams['font.family'] = 'AppleGothic Gothic' # Mac사용자
matplotlib.rcParams['font.size'] = '10' # 글자크기

In [8]:
(train_input,train_target),(test_input,test_target) = keras.datasets.fashion_mnist.load_data()
train_scaled =train_input/255.0

In [9]:
train_scaled,val_scaled,train_target,val_target = train_test_split(
    train_scaled,train_target,test_size=0.2,random_state=42
)

In [10]:
model = keras.Sequential()
model.add(keras.layers.Flatten(input_shape=(28,28))) #train_input.shape 사이즈이다
model.add(keras.layers.Dense(100,activation='relu')) #규제해서 랜덤으로 70개만사용
model.add(keras.layers.Dropout(0.3)) # 30%를 제외시키는 규제를 적용시키는것이다(계속 확인)
model.add(keras.layers.Dense(10,activation='softmax'))

In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 100)            │        78,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 238,532 (931.77 KB)

 Trainable params: 79,510 (310.59 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 159,022 (621.18 KB)

In [ ]:
# model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
# # epochs 돌때마다 loss,accuracy 값을 저장.
# # train_scaled,val_scaled 함께 훈련시킴.
# history = model.fit(train_scaled,train_target,epochs=20,
#                     validation_data=(val_scaled,val_target))

## 불러서 사용해보기

In [13]:
model.load_weights('model0529.weights.h5')

In [15]:
model.predict(val_scaled)

375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


array([[2.0299095e-14, 3.4631003e-16, 2.7408429e-17, ..., 4.9874358e-12,
        1.0000000e+00, 1.2212987e-19],
       [1.1639955e-05, 6.1476942e-11, 4.8568869e-05, ..., 9.7702922e-13,
        9.9984431e-01, 5.8187835e-13],
       [1.9629784e-13, 2.5540198e-11, 2.0075321e-14, ..., 9.9958104e-01,
        4.8969561e-12, 1.1205247e-07],
       ...,
       [3.8070255e-05, 2.1270175e-12, 1.2884088e-06, ..., 5.5352177e-07,
        9.9967635e-01, 1.3451836e-07],
       [3.8498382e-13, 3.6465976e-19, 2.2289380e-15, ..., 1.0499293e-12,
        1.0000000e+00, 5.5399689e-18],
       [1.5227485e-01, 8.1681363e-05, 3.9495621e-02, ..., 3.8091892e-03,
        6.9575879e-04, 7.3528201e-03]], dtype=float32)

In [18]:
val_target

array([8, 8, 7, ..., 8, 8, 1], dtype=uint8)

In [17]:
val_labels = np.argmax(model.predict(val_scaled),axis=-1) #높은값의 평균값을 해서 보여준다..
np.mean(val_labels == val_target) # 가장높은 값중에 정답과 일치한 것만 평균으로 적용

375/375 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


0.8841666666666667

In [19]:
val_labels

array([8, 8, 7, ..., 8, 8, 6], dtype=int64)

### 모델 전체를 저장한것을 불러와서 처리

In [20]:
model = keras.models.load_model('model_all.h5')

In [21]:
model.evaluate(val_scaled,val_target)

375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8833 - loss: 0.3189


[0.3200347125530243, 0.8841666579246521]